use signal_persona::{PERSONA_INTERFACE_RUST, PERSONA_INTERFACE_SOURCE, bootstrap_manifest};

#[test]
fn canonical_source_is_a_role_free_types_only_interface() {
    assert!(PERSONA_INTERFACE_SOURCE.starts_with("Interface.{1 0 0}\n[]\n{"));
    assert!(PERSONA_INTERFACE_SOURCE.contains("LifecycleRequest.["));
    assert!(PERSONA_INTERFACE_SOURCE.contains("LifecycleReply.["));
    assert!(PERSONA_INTERFACE_SOURCE.contains("\n  []\n  []\n  []\n  ["));
    assert!(!PERSONA_INTERFACE_SOURCE.contains("Optional."));
}

#[test]
fn strict_projection_uses_only_encoded_rust_coordinates() {
    assert!(PERSONA_INTERFACE_RUST.starts_with(
        "// @generated by schema-rust from an authority-verified bootstrap Interface\n\n"
    ));
    for visible in ["LifecycleRequest", "LifecycleReply", "SpawnEnvelope"] {
        assert!(!PERSONA_INTERFACE_RUST.contains(&format!("pub enum {visible}")));
        assert!(!PERSONA_INTERFACE_RUST.contains(&format!("pub struct {visible}")));
    }
    assert!(bootstrap_manifest::DECLARATION_SEATS.len() > 100);
}
