// @generated by schema-rust from an authority-verified bootstrap Interface

pub struct z2VQrC {
    pub field_0: z2VRUd,
    pub field_1: z2VPho,
    pub field_2: z2VMoT,
}
pub struct z2VRbW(std::string::String);
impl z2VRbW {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWB7 {
    pub field_0: z2VRuG,
    pub field_1: z2VS4Z,
}
pub struct z2VRUd ( z2VUT8 ,) ;
pub enum z2VRBs {z2VXB3 ( z2VcJJ ,) , z2VWNV ( z2VaTc ,) ,} 
pub struct z2VMoT(u64);
impl z2VMoT {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VbVt {z2VVRJ , z2VPCR , z2Va7G ,} 
pub struct z2VWYF {
    pub field_0: z2VUT8,
    pub field_1: z2VXzu,
    pub field_2: z2VYY4,
    pub field_3: z2VRTx,
}
pub struct z2VQEa(Option<z2VUtF>);
impl z2VQEa {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Option<z2VUtF>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Option<z2VUtF> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Option<z2VUtF> {
        self.0
    }
}
pub struct z2VWLR {
    pub field_0: z2VRuG,
    pub field_1: z2VXzu,
    pub field_2: z2VPCG,
    pub field_3: z2VRBs,
    pub field_4: z2VWbh,
    pub field_5: z2Veez,
    pub field_6: z2VNyf,
    pub field_7: z2VckR,
    pub field_8: z2VSSX,
    pub field_9: Vec<z2VdUt>,
    pub field_10: z2VSQQ,
    pub field_11: z2VMoT,
}
pub struct z2VaTc(u64);
impl z2VaTc {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VN5e(std::string::String);
impl z2VN5e {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWXM ( z2VeMi ,) ;
pub struct z2VaBZ ( z2VTjH ,) ;
pub enum z2VWMn {z2VYDy ( z2VQEa ,) , z2VdiG ( z2VaBZ ,) , z2VTp5 ( z2VNEZ ,) , z2VMBi ( z2VSo2 ,) , z2VUnp ( z2VYBe ,) , z2VXTU ( z2VP8n ,) ,} 
pub enum z2VPCG {z2Vd4e , z2VRDc , z2VRn6 , z2VSGN , z2VbwP , z2VdrW , z2Vc4x , z2VRFB , z2VRoL ,} 
pub struct z2VNo7(std::string::String);
impl z2VNo7 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VRTx {z2Vcq1 , z2VaNa , z2VcFR , z2VNhK , z2VfAo ,} 
pub struct z2VSo2 {
    pub field_0: z2VUT8,
    pub field_1: z2VXzu,
    pub field_2: z2VMoT,
    pub field_3: Option<z2Vb2D>,
}
pub struct z2VUtF(u64);
impl z2VUtF {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VdUt {
    pub field_0: z2VPCG,
    pub field_1: z2Veez,
}
pub struct z2Vcky(std::string::String);
impl z2Vcky {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2VTjH {z2VeKJ , z2VX6Y ( z2VVUX ,) , z2Vca6 ( z2VSfT ,) ,} 
pub struct z2VNEZ ( z2VRTx ,) ;
pub struct z2VNyf(u64);
impl z2VNyf {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub enum z2VXzu {z2VWpQ , z2VQRH , z2VWaX , z2VMDy , z2VVyZ , z2VLJC , z2VWUK , z2VKp5 , z2VT9K ,} 
pub enum z2VZ7N {z2VN5r ( z2VUT8 ,) , z2VMrM ( z2VUT8 ,) ,} 
pub enum z2VeMi {z2VbBv ( z2VNuR ,) , z2VYqK ( z2VRBs ,) , z2Vb7o ( z2VPCG ,) , z2VPgY ( z2VNo7 ,) , z2VVJG ( z2VL2r ,) ,} 
pub enum z2VSfT {z2VMgV , z2VLH2 , z2VVmM ,} 
pub struct z2VckR(std::string::String);
impl z2VckR {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VSSX(u64);
impl z2VSSX {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
pub struct z2VSQQ(std::string::String);
impl z2VSQQ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2Vb2D {z2VYrz , z2VaiE , z2VRWY ,} 
pub struct z2VUT8(std::string::String);
impl z2VUT8 {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub enum z2Vbqz {z2VQes ( z2VZ7N ,) , z2VRix ( z2VQrC ,) , z2VPCE ( z2VUT8 ,) ,} 
pub enum z2VL2r {z2VamY ( z2VN5e ,) , z2VSY8 ( z2VWB7 ,) , z2VTUm , z2VWpJ ( z2VaTc ,) , z2Vezo ( z2VcJJ ,) ,} 
pub struct z2VS4Z ( z2Vcky ,) ;
pub enum z2VYY4 {z2Ve2k , z2VdTN ,} 
pub enum z2VVUX {z2VVnV ,} 
pub struct z2VPho ( z2VXzu ,) ;
pub struct z2VP8n ( z2VbVt ,) ;
pub struct z2Veez(std::string::String);
impl z2Veez {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VNuR {
    pub field_0: z2VPCG,
    pub field_1: z2VRbW,
}
pub struct z2VYBe(Option<z2VUtF>);
impl z2VYBe {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: Option<z2VUtF>) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &Option<z2VUtF> {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> Option<z2VUtF> {
        self.0
    }
}
pub struct z2VcJJ(std::string::String);
impl z2VcJJ {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VRuG(std::string::String);
impl z2VRuG {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
pub struct z2VWbh(std::string::String);
impl z2VWbh {
    /// Construct the generated newtype from its source-declared payload.
    pub fn new(payload: std::string::String) -> Self {
        Self(payload)
    }
    /// Borrow the one source-declared payload without decoding archive bytes.
    pub fn payload(&self) -> &std::string::String {
        &self.0
    }
    /// Consume the newtype and recover its source-declared payload.
    pub fn into_payload(self) -> std::string::String {
        self.0
    }
}
