// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota_next::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Announce(Presence);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(LifecycleQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stop(ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Identified(ComponentIdentity);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Ready(ComponentReady);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NotReady(ComponentNotReady);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HealthReport(ComponentHealthReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopAcknowledged(StopAcknowledgement);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Unimplemented(RequestUnimplemented);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentInstanceName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPeer(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentKind {
    Mind,
    Router,
    Message,
    System,
    Harness,
    Terminal,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentPrincipal {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentHealth {
    Starting,
    Running,
    Degraded,
    Stopped,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentDesiredState {
    Running,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentStatus {
    pub component_name: ComponentName,
    pub component_kind: ComponentKind,
    pub component_desired_state: ComponentDesiredState,
    pub component_health: ComponentHealth,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementProtocolVersion(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDirectoryPath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ManagerSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainSocketMode(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementSocketMode(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanoseconds(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentStartupError {
    SocketBindFailed,
    StoreOpenFailed,
    EnvelopeIncomplete,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentNotReadyReason {
    NotYetBound,
    AwaitingDependency,
    RecoveringFromCrash,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExpectedComponent(ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExpectedKind(ComponentKind);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Presence {
    pub expected_component: ExpectedComponent,
    pub expected_kind: ExpectedKind,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct LastFatalStartupError(Option<ComponentStartupError>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentIdentity {
    pub component_name: ComponentName,
    pub component_kind: ComponentKind,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
    pub(crate) last_fatal_startup_error: LastFatalStartupError,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ComponentStartedAt(Option<TimestampNanoseconds>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentReady(ComponentStartedAt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentNotReady(ComponentNotReadyReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentHealthReport(ComponentHealth);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct DrainCompletedAt(Option<TimestampNanoseconds>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopAcknowledgement(DrainCompletedAt);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DependencyKind {
    PeerComponent,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ResourceKind {
    ManagerSocket,
    SocketPath,
    StateDirectory,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
    DependencyMissing(DependencyKind),
    ResourceUnavailable(ResourceKind),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Host(HostName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: Host,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InternalComponentInstanceOrigin {
    pub component_principal: ComponentPrincipal,
    pub component_instance_name: ComponentInstanceName,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageOrigin {
    LocalOwner(OwnerIdentity),
    LocalConnection(ConnectionClass),
    Internal(ComponentPrincipal),
    InternalComponentInstance(InternalComponentInstanceOrigin),
    Channel(ChannelIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IngressContext(MessageOrigin);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PeerSocket {
    pub component_principal: ComponentPrincipal,
    pub domain_socket_path: DomainSocketPath,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PeerSockets(Vec<PeerSocket>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SpawnEnvelope {
    pub engine_identifier: EngineIdentifier,
    pub component_kind: ComponentKind,
    pub component_principal: ComponentPrincipal,
    pub owner_identity: OwnerIdentity,
    pub state_directory_path: StateDirectoryPath,
    pub domain_socket_path: DomainSocketPath,
    pub domain_socket_mode: DomainSocketMode,
    pub engine_management_socket_path: EngineManagementSocketPath,
    pub engine_management_socket_mode: EngineManagementSocketMode,
    pub(crate) peer_sockets: PeerSockets,
    pub manager_socket_path: ManagerSocketPath,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LifecycleQuery {
    ReadinessStatus(ComponentName),
    HealthStatus(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Announce(Announce),
    Query(Query),
    Stop(Stop),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Identified(Identified),
    Ready(Ready),
    NotReady(NotReady),
    HealthReport(HealthReport),
    StopAcknowledged(StopAcknowledged),
    Unimplemented(Unimplemented),
}

#[rustfmt::skip]
impl Announce {
    pub fn new(payload: Presence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Presence {
        &self.0
    }
    pub fn into_payload(self) -> Presence {
        self.0
    }
}
#[rustfmt::skip]
impl From<Presence> for Announce {
    fn from(payload: Presence) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: LifecycleQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LifecycleQuery {
        &self.0
    }
    pub fn into_payload(self) -> LifecycleQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<LifecycleQuery> for Query {
    fn from(payload: LifecycleQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stop {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for Stop {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Identified {
    pub fn new(payload: ComponentIdentity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentIdentity {
        &self.0
    }
    pub fn into_payload(self) -> ComponentIdentity {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentIdentity> for Identified {
    fn from(payload: ComponentIdentity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Ready {
    pub fn new(payload: ComponentReady) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentReady {
        &self.0
    }
    pub fn into_payload(self) -> ComponentReady {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentReady> for Ready {
    fn from(payload: ComponentReady) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NotReady {
    pub fn new(payload: ComponentNotReady) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentNotReady {
        &self.0
    }
    pub fn into_payload(self) -> ComponentNotReady {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentNotReady> for NotReady {
    fn from(payload: ComponentNotReady) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HealthReport {
    pub fn new(payload: ComponentHealthReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentHealthReport {
        &self.0
    }
    pub fn into_payload(self) -> ComponentHealthReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentHealthReport> for HealthReport {
    fn from(payload: ComponentHealthReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopAcknowledged {
    pub fn new(payload: StopAcknowledgement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StopAcknowledgement {
        &self.0
    }
    pub fn into_payload(self) -> StopAcknowledgement {
        self.0
    }
}
#[rustfmt::skip]
impl From<StopAcknowledgement> for StopAcknowledged {
    fn from(payload: StopAcknowledgement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Unimplemented {
    pub fn new(payload: RequestUnimplemented) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RequestUnimplemented {
        &self.0
    }
    pub fn into_payload(self) -> RequestUnimplemented {
        self.0
    }
}
#[rustfmt::skip]
impl From<RequestUnimplemented> for Unimplemented {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ComponentName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ComponentName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ComponentName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for EngineIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for EngineIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for EngineIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ChannelIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ChannelIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ChannelIdentifier {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ChannelIdentifier {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ChannelIdentifier {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ComponentInstanceName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentInstanceName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ComponentInstanceName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ComponentInstanceName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ComponentInstanceName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for HostName {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for HostName {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for HostName {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for SystemPrincipal {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for SystemPrincipal {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for SystemPrincipal {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for UnixUserIdentifier {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkPeer {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkPeer {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for NetworkPeer {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for NetworkPeer {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for NetworkPeer {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineManagementProtocolVersion {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for EngineManagementProtocolVersion {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDirectoryPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StateDirectoryPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for StateDirectoryPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for StateDirectoryPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for StateDirectoryPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl DomainSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DomainSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for DomainSocketPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for DomainSocketPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for DomainSocketPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineManagementSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineManagementSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for EngineManagementSocketPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for EngineManagementSocketPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for EngineManagementSocketPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl ManagerSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ManagerSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for ManagerSocketPath {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for ManagerSocketPath {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for ManagerSocketPath {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl DomainSocketMode {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for DomainSocketMode {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineManagementSocketMode {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for EngineManagementSocketMode {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanoseconds {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for TimestampNanoseconds {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExpectedComponent {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for ExpectedComponent {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExpectedKind {
    pub fn new(payload: ComponentKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentKind {
        &self.0
    }
    pub fn into_payload(self) -> ComponentKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentKind> for ExpectedKind {
    fn from(payload: ComponentKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LastFatalStartupError {
    pub fn new(payload: Option<ComponentStartupError>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ComponentStartupError> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ComponentStartupError> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ComponentStartupError>> for LastFatalStartupError {
    fn from(payload: Option<ComponentStartupError>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentStartedAt {
    pub fn new(payload: Option<TimestampNanoseconds>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TimestampNanoseconds> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TimestampNanoseconds> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TimestampNanoseconds>> for ComponentStartedAt {
    fn from(payload: Option<TimestampNanoseconds>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentReady {
    pub fn new(payload: ComponentStartedAt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentStartedAt {
        &self.0
    }
    pub fn into_payload(self) -> ComponentStartedAt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentStartedAt> for ComponentReady {
    fn from(payload: ComponentStartedAt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentNotReady {
    pub fn new(payload: ComponentNotReadyReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentNotReadyReason {
        &self.0
    }
    pub fn into_payload(self) -> ComponentNotReadyReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentNotReadyReason> for ComponentNotReady {
    fn from(payload: ComponentNotReadyReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentHealthReport {
    pub fn new(payload: ComponentHealth) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentHealth {
        &self.0
    }
    pub fn into_payload(self) -> ComponentHealth {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentHealth> for ComponentHealthReport {
    fn from(payload: ComponentHealth) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DrainCompletedAt {
    pub fn new(payload: Option<TimestampNanoseconds>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TimestampNanoseconds> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TimestampNanoseconds> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TimestampNanoseconds>> for DrainCompletedAt {
    fn from(payload: Option<TimestampNanoseconds>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopAcknowledgement {
    pub fn new(payload: DrainCompletedAt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DrainCompletedAt {
        &self.0
    }
    pub fn into_payload(self) -> DrainCompletedAt {
        self.0
    }
}
#[rustfmt::skip]
impl From<DrainCompletedAt> for StopAcknowledgement {
    fn from(payload: DrainCompletedAt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Host {
    pub fn new(payload: HostName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HostName {
        &self.0
    }
    pub fn into_payload(self) -> HostName {
        self.0
    }
}
#[rustfmt::skip]
impl From<HostName> for Host {
    fn from(payload: HostName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IngressContext {
    pub fn new(payload: MessageOrigin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageOrigin {
        &self.0
    }
    pub fn into_payload(self) -> MessageOrigin {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageOrigin> for IngressContext {
    fn from(payload: MessageOrigin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PeerSockets {
    pub fn new(payload: Vec<PeerSocket>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<PeerSocket> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<PeerSocket> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<PeerSocket>> for PeerSockets {
    fn from(payload: Vec<PeerSocket>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnimplementedReason {
    pub fn dependency_missing(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
    pub fn resource_unavailable(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: u64) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl ConnectionClass {
    pub fn non_owner_user(payload: u64) -> Self {
        Self::NonOwnerUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
    pub fn network(payload: String) -> Self {
        Self::Network(NetworkPeer::new(payload))
    }
}

#[rustfmt::skip]
impl MessageOrigin {
    pub fn local_owner(payload: OwnerIdentity) -> Self {
        Self::LocalOwner(payload)
    }
    pub fn local_connection(payload: ConnectionClass) -> Self {
        Self::LocalConnection(payload)
    }
    pub fn internal(payload: ComponentPrincipal) -> Self {
        Self::Internal(payload)
    }
    pub fn internal_component_instance(
        payload: InternalComponentInstanceOrigin,
    ) -> Self {
        Self::InternalComponentInstance(payload)
    }
    pub fn channel(payload: String) -> Self {
        Self::Channel(ChannelIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl LifecycleQuery {
    pub fn readiness_status(payload: String) -> Self {
        Self::ReadinessStatus(ComponentName::new(payload))
    }
    pub fn health_status(payload: String) -> Self {
        Self::HealthStatus(ComponentName::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn announce(payload: Presence) -> Self {
        Self::Announce(Announce::new(payload))
    }
    pub fn query(payload: LifecycleQuery) -> Self {
        Self::Query(Query::new(payload))
    }
    pub fn stop(payload: ComponentName) -> Self {
        Self::Stop(Stop::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn identified(payload: ComponentIdentity) -> Self {
        Self::Identified(Identified::new(payload))
    }
    pub fn ready(payload: ComponentReady) -> Self {
        Self::Ready(Ready::new(payload))
    }
    pub fn not_ready(payload: ComponentNotReady) -> Self {
        Self::NotReady(NotReady::new(payload))
    }
    pub fn health_report(payload: ComponentHealthReport) -> Self {
        Self::HealthReport(HealthReport::new(payload))
    }
    pub fn stop_acknowledged(payload: StopAcknowledgement) -> Self {
        Self::StopAcknowledged(StopAcknowledged::new(payload))
    }
    pub fn unimplemented(payload: RequestUnimplemented) -> Self {
        Self::Unimplemented(Unimplemented::new(payload))
    }
}

#[rustfmt::skip]
impl From<DependencyKind> for UnimplementedReason {
    fn from(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
}

#[rustfmt::skip]
impl From<ResourceKind> for UnimplementedReason {
    fn from(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for ConnectionClass {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for ConnectionClass {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkPeer> for ConnectionClass {
    fn from(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

#[rustfmt::skip]
impl From<OwnerIdentity> for MessageOrigin {
    fn from(payload: OwnerIdentity) -> Self {
        Self::LocalOwner(payload)
    }
}

#[rustfmt::skip]
impl From<ConnectionClass> for MessageOrigin {
    fn from(payload: ConnectionClass) -> Self {
        Self::LocalConnection(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentPrincipal> for MessageOrigin {
    fn from(payload: ComponentPrincipal) -> Self {
        Self::Internal(payload)
    }
}

#[rustfmt::skip]
impl From<InternalComponentInstanceOrigin> for MessageOrigin {
    fn from(payload: InternalComponentInstanceOrigin) -> Self {
        Self::InternalComponentInstance(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelIdentifier> for MessageOrigin {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::Channel(payload)
    }
}

#[rustfmt::skip]
impl From<Announce> for Input {
    fn from(payload: Announce) -> Self {
        Self::Announce(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<Stop> for Input {
    fn from(payload: Stop) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<Identified> for Output {
    fn from(payload: Identified) -> Self {
        Self::Identified(payload)
    }
}

#[rustfmt::skip]
impl From<Ready> for Output {
    fn from(payload: Ready) -> Self {
        Self::Ready(payload)
    }
}

#[rustfmt::skip]
impl From<NotReady> for Output {
    fn from(payload: NotReady) -> Self {
        Self::NotReady(payload)
    }
}

#[rustfmt::skip]
impl From<HealthReport> for Output {
    fn from(payload: HealthReport) -> Self {
        Self::HealthReport(payload)
    }
}

#[rustfmt::skip]
impl From<StopAcknowledged> for Output {
    fn from(payload: StopAcknowledged) -> Self {
        Self::StopAcknowledged(payload)
    }
}

#[rustfmt::skip]
impl From<Unimplemented> for Output {
    fn from(payload: Unimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_ANNOUNCE: u64 = 0x0000000000000000;
    pub const INPUT_QUERY: u64 = 0x0001000000000000;
    pub const INPUT_STOP: u64 = 0x0002000000000000;
    pub const OUTPUT_IDENTIFIED: u64 = 0x0100000000000000;
    pub const OUTPUT_READY: u64 = 0x0101000000000000;
    pub const OUTPUT_NOT_READY: u64 = 0x0102000000000000;
    pub const OUTPUT_HEALTH_REPORT: u64 = 0x0103000000000000;
    pub const OUTPUT_STOP_ACKNOWLEDGED: u64 = 0x0104000000000000;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0105000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Announce,
    Query,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota_next::NotaDecode, nota_next::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Identified,
    Ready,
    NotReady,
    HealthReport,
    StopAcknowledged,
    Unimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Announce(_) => InputRoute::Announce,
            Self::Query(_) => InputRoute::Query,
            Self::Stop(_) => InputRoute::Stop,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Announce(_) => short_header::INPUT_ANNOUNCE,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::Stop(_) => short_header::INPUT_STOP,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_ANNOUNCE => Ok(InputRoute::Announce),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_STOP => Ok(InputRoute::Stop),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Identified(_) => OutputRoute::Identified,
            Self::Ready(_) => OutputRoute::Ready,
            Self::NotReady(_) => OutputRoute::NotReady,
            Self::HealthReport(_) => OutputRoute::HealthReport,
            Self::StopAcknowledged(_) => OutputRoute::StopAcknowledged,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Identified(_) => short_header::OUTPUT_IDENTIFIED,
            Self::Ready(_) => short_header::OUTPUT_READY,
            Self::NotReady(_) => short_header::OUTPUT_NOT_READY,
            Self::HealthReport(_) => short_header::OUTPUT_HEALTH_REPORT,
            Self::StopAcknowledged(_) => short_header::OUTPUT_STOP_ACKNOWLEDGED,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_IDENTIFIED => Ok(OutputRoute::Identified),
            short_header::OUTPUT_READY => Ok(OutputRoute::Ready),
            short_header::OUTPUT_NOT_READY => Ok(OutputRoute::NotReady),
            short_header::OUTPUT_HEALTH_REPORT => Ok(OutputRoute::HealthReport),
            short_header::OUTPUT_STOP_ACKNOWLEDGED => Ok(OutputRoute::StopAcknowledged),
            short_header::OUTPUT_UNIMPLEMENTED => Ok(OutputRoute::Unimplemented),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Announce", "Query", "Stop"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
