// @generated by schema-rust

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
pub use dotos::{DotosDecodeError, DotosEncode, DotosSource};

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Announce(Presence);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(LifecycleQuery);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stop(ComponentName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Identified(ComponentIdentity);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Ready(ComponentReady);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NotReady(ComponentNotReady);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HealthReport(ComponentHealthReport);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopAcknowledged(StopAcknowledgement);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Unimplemented(RequestUnimplemented);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ChannelIdentifier(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentInstanceName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct HostName(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SystemPrincipal(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct UnixUserIdentifier(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct NetworkPeer(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentKind {
    Mind,
    Router,
    Message,
    System,
    Harness,
    Terminal,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentPrincipal {
    Mind,
    Message,
    Router,
    Terminal,
    Harness,
    System,
    Introspect,
    Orchestrate,
    Spirit,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentHealth {
    Starting,
    Running,
    Degraded,
    Stopped,
    Failed,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentDesiredState {
    Running,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentStatus {
    pub component_name: ComponentName,
    pub component_kind: ComponentKind,
    pub component_desired_state: ComponentDesiredState,
    pub component_health: ComponentHealth,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementProtocolVersion(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StateDirectoryPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ManagerSocketPath(String);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct DomainSocketMode(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineManagementSocketMode(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct TimestampNanoseconds(u64);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentStartupError {
    SocketBindFailed,
    StoreOpenFailed,
    EnvelopeIncomplete,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ComponentNotReadyReason {
    NotYetBound,
    AwaitingDependency,
    RecoveringFromCrash,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExpectedComponent(ComponentName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ExpectedKind(ComponentKind);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Presence {
    pub expected_component: ExpectedComponent,
    pub expected_kind: ExpectedKind,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct LastFatalStartupError(Option<ComponentStartupError>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentIdentity {
    pub component_name: ComponentName,
    pub component_kind: ComponentKind,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
    pub(crate) last_fatal_startup_error: LastFatalStartupError,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct ComponentStartedAt(Option<TimestampNanoseconds>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentReady(ComponentStartedAt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentNotReady(ComponentNotReadyReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentHealthReport(ComponentHealth);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct DrainCompletedAt(Option<TimestampNanoseconds>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct StopAcknowledgement(DrainCompletedAt);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum DependencyKind {
    PeerComponent,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ResourceKind {
    ManagerSocket,
    SocketPath,
    StateDirectory,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum UnimplementedReason {
    NotInPrototypeScope,
    DependencyMissing(DependencyKind),
    ResourceUnavailable(ResourceKind),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RequestUnimplemented(UnimplementedReason);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum OwnerIdentity {
    UnixUser(UnixUserIdentifier),
    System(SystemPrincipal),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Host(HostName);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct OtherPersonaEngine {
    pub engine_identifier: EngineIdentifier,
    pub host: Host,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum ConnectionClass {
    Owner,
    NonOwnerUser(UnixUserIdentifier),
    System(SystemPrincipal),
    OtherPersona(OtherPersonaEngine),
    Network(NetworkPeer),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct InternalComponentInstanceOrigin {
    pub component_principal: ComponentPrincipal,
    pub component_instance_name: ComponentInstanceName,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MessageOrigin {
    LocalOwner(OwnerIdentity),
    LocalConnection(ConnectionClass),
    Internal(ComponentPrincipal),
    InternalComponentInstance(InternalComponentInstanceOrigin),
    Channel(ChannelIdentifier),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct IngressContext(MessageOrigin);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct PeerSocket {
    pub component_principal: ComponentPrincipal,
    pub domain_socket_path: DomainSocketPath,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub(crate) struct PeerSockets(Vec<PeerSocket>);

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct SpawnEnvelope {
    pub engine_identifier: EngineIdentifier,
    pub component_kind: ComponentKind,
    pub component_principal: ComponentPrincipal,
    pub owner_identity: OwnerIdentity,
    pub state_directory_path: StateDirectoryPath,
    pub domain_socket_path: DomainSocketPath,
    pub domain_socket_mode: DomainSocketMode,
    pub engine_management_socket_path: EngineManagementSocketPath,
    pub engine_management_socket_mode: EngineManagementSocketMode,
    pub(crate) peer_sockets: PeerSockets,
    pub manager_socket_path: ManagerSocketPath,
    pub engine_management_protocol_version: EngineManagementProtocolVersion,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum LifecycleQuery {
    ReadinessStatus(ComponentName),
    HealthStatus(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Announce(Presence),
    Query(LifecycleQuery),
    Stop(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Identified(ComponentIdentity),
    Ready(ComponentReady),
    NotReady(ComponentNotReady),
    HealthReport(ComponentHealthReport),
    StopAcknowledged(StopAcknowledgement),
    Unimplemented(RequestUnimplemented),
}

#[rustfmt::skip]
impl Announce {
    pub fn new(payload: Presence) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Presence {
        &self.0
    }
    pub fn into_payload(self) -> Presence {
        self.0
    }
}
#[rustfmt::skip]
impl From<Presence> for Announce {
    fn from(payload: Presence) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: LifecycleQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LifecycleQuery {
        &self.0
    }
    pub fn into_payload(self) -> LifecycleQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<LifecycleQuery> for Query {
    fn from(payload: LifecycleQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stop {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for Stop {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Identified {
    pub fn new(payload: ComponentIdentity) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentIdentity {
        &self.0
    }
    pub fn into_payload(self) -> ComponentIdentity {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentIdentity> for Identified {
    fn from(payload: ComponentIdentity) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Ready {
    pub fn new(payload: ComponentReady) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentReady {
        &self.0
    }
    pub fn into_payload(self) -> ComponentReady {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentReady> for Ready {
    fn from(payload: ComponentReady) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NotReady {
    pub fn new(payload: ComponentNotReady) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentNotReady {
        &self.0
    }
    pub fn into_payload(self) -> ComponentNotReady {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentNotReady> for NotReady {
    fn from(payload: ComponentNotReady) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HealthReport {
    pub fn new(payload: ComponentHealthReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentHealthReport {
        &self.0
    }
    pub fn into_payload(self) -> ComponentHealthReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentHealthReport> for HealthReport {
    fn from(payload: ComponentHealthReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopAcknowledged {
    pub fn new(payload: StopAcknowledgement) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &StopAcknowledgement {
        &self.0
    }
    pub fn into_payload(self) -> StopAcknowledgement {
        self.0
    }
}
#[rustfmt::skip]
impl From<StopAcknowledgement> for StopAcknowledged {
    fn from(payload: StopAcknowledgement) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Unimplemented {
    pub fn new(payload: RequestUnimplemented) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RequestUnimplemented {
        &self.0
    }
    pub fn into_payload(self) -> RequestUnimplemented {
        self.0
    }
}
#[rustfmt::skip]
impl From<RequestUnimplemented> for Unimplemented {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ChannelIdentifier {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ChannelIdentifier {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentInstanceName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ComponentInstanceName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl HostName {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for HostName {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl SystemPrincipal {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for SystemPrincipal {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnixUserIdentifier {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for UnixUserIdentifier {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl NetworkPeer {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for NetworkPeer {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineManagementProtocolVersion {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for EngineManagementProtocolVersion {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StateDirectoryPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for StateDirectoryPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for DomainSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineManagementSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineManagementSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ManagerSocketPath {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for ManagerSocketPath {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DomainSocketMode {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for DomainSocketMode {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineManagementSocketMode {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for EngineManagementSocketMode {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl TimestampNanoseconds {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for TimestampNanoseconds {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExpectedComponent {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for ExpectedComponent {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ExpectedKind {
    pub fn new(payload: ComponentKind) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentKind {
        &self.0
    }
    pub fn into_payload(self) -> ComponentKind {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentKind> for ExpectedKind {
    fn from(payload: ComponentKind) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LastFatalStartupError {
    pub fn new(payload: Option<ComponentStartupError>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<ComponentStartupError> {
        &self.0
    }
    pub fn into_payload(self) -> Option<ComponentStartupError> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<ComponentStartupError>> for LastFatalStartupError {
    fn from(payload: Option<ComponentStartupError>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentStartedAt {
    pub fn new(payload: Option<TimestampNanoseconds>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TimestampNanoseconds> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TimestampNanoseconds> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TimestampNanoseconds>> for ComponentStartedAt {
    fn from(payload: Option<TimestampNanoseconds>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentReady {
    pub fn new(payload: ComponentStartedAt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentStartedAt {
        &self.0
    }
    pub fn into_payload(self) -> ComponentStartedAt {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentStartedAt> for ComponentReady {
    fn from(payload: ComponentStartedAt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentNotReady {
    pub fn new(payload: ComponentNotReadyReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentNotReadyReason {
        &self.0
    }
    pub fn into_payload(self) -> ComponentNotReadyReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentNotReadyReason> for ComponentNotReady {
    fn from(payload: ComponentNotReadyReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentHealthReport {
    pub fn new(payload: ComponentHealth) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentHealth {
        &self.0
    }
    pub fn into_payload(self) -> ComponentHealth {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentHealth> for ComponentHealthReport {
    fn from(payload: ComponentHealth) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl DrainCompletedAt {
    pub fn new(payload: Option<TimestampNanoseconds>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Option<TimestampNanoseconds> {
        &self.0
    }
    pub fn into_payload(self) -> Option<TimestampNanoseconds> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Option<TimestampNanoseconds>> for DrainCompletedAt {
    fn from(payload: Option<TimestampNanoseconds>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl StopAcknowledgement {
    pub fn new(payload: DrainCompletedAt) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &DrainCompletedAt {
        &self.0
    }
    pub fn into_payload(self) -> DrainCompletedAt {
        self.0
    }
}
#[rustfmt::skip]
impl From<DrainCompletedAt> for StopAcknowledgement {
    fn from(payload: DrainCompletedAt) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RequestUnimplemented {
    pub fn new(payload: UnimplementedReason) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &UnimplementedReason {
        &self.0
    }
    pub fn into_payload(self) -> UnimplementedReason {
        self.0
    }
}
#[rustfmt::skip]
impl From<UnimplementedReason> for RequestUnimplemented {
    fn from(payload: UnimplementedReason) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Host {
    pub fn new(payload: HostName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &HostName {
        &self.0
    }
    pub fn into_payload(self) -> HostName {
        self.0
    }
}
#[rustfmt::skip]
impl From<HostName> for Host {
    fn from(payload: HostName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl IngressContext {
    pub fn new(payload: MessageOrigin) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MessageOrigin {
        &self.0
    }
    pub fn into_payload(self) -> MessageOrigin {
        self.0
    }
}
#[rustfmt::skip]
impl From<MessageOrigin> for IngressContext {
    fn from(payload: MessageOrigin) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl PeerSockets {
    pub fn new(payload: Vec<PeerSocket>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<PeerSocket> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<PeerSocket> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<PeerSocket>> for PeerSockets {
    fn from(payload: Vec<PeerSocket>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl UnimplementedReason {
    pub fn dependency_missing(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
    pub fn resource_unavailable(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl OwnerIdentity {
    pub fn unix_user(payload: u64) -> Self {
        Self::UnixUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
}

#[rustfmt::skip]
impl ConnectionClass {
    pub fn non_owner_user(payload: u64) -> Self {
        Self::NonOwnerUser(UnixUserIdentifier::new(payload))
    }
    pub fn system(payload: String) -> Self {
        Self::System(SystemPrincipal::new(payload))
    }
    pub fn other_persona(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
    pub fn network(payload: String) -> Self {
        Self::Network(NetworkPeer::new(payload))
    }
}

#[rustfmt::skip]
impl MessageOrigin {
    pub fn local_owner(payload: OwnerIdentity) -> Self {
        Self::LocalOwner(payload)
    }
    pub fn local_connection(payload: ConnectionClass) -> Self {
        Self::LocalConnection(payload)
    }
    pub fn internal(payload: ComponentPrincipal) -> Self {
        Self::Internal(payload)
    }
    pub fn internal_component_instance(
        payload: InternalComponentInstanceOrigin,
    ) -> Self {
        Self::InternalComponentInstance(payload)
    }
    pub fn channel(payload: String) -> Self {
        Self::Channel(ChannelIdentifier::new(payload))
    }
}

#[rustfmt::skip]
impl LifecycleQuery {
    pub fn readiness_status(payload: String) -> Self {
        Self::ReadinessStatus(ComponentName::new(payload))
    }
    pub fn health_status(payload: String) -> Self {
        Self::HealthStatus(ComponentName::new(payload))
    }
}

#[rustfmt::skip]
impl Input {
    pub fn announce(payload: Presence) -> Self {
        Self::Announce(payload)
    }
    pub fn query(payload: LifecycleQuery) -> Self {
        Self::Query(payload)
    }
    pub fn stop(payload: String) -> Self {
        Self::Stop(ComponentName::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn identified(payload: ComponentIdentity) -> Self {
        Self::Identified(payload)
    }
    pub fn ready(payload: ComponentStartedAt) -> Self {
        Self::Ready(ComponentReady::new(payload))
    }
    pub fn not_ready(payload: ComponentNotReadyReason) -> Self {
        Self::NotReady(ComponentNotReady::new(payload))
    }
    pub fn health_report(payload: ComponentHealth) -> Self {
        Self::HealthReport(ComponentHealthReport::new(payload))
    }
    pub fn stop_acknowledged(payload: DrainCompletedAt) -> Self {
        Self::StopAcknowledged(StopAcknowledgement::new(payload))
    }
    pub fn unimplemented(payload: UnimplementedReason) -> Self {
        Self::Unimplemented(RequestUnimplemented::new(payload))
    }
}

#[rustfmt::skip]
impl From<DependencyKind> for UnimplementedReason {
    fn from(payload: DependencyKind) -> Self {
        Self::DependencyMissing(payload)
    }
}

#[rustfmt::skip]
impl From<ResourceKind> for UnimplementedReason {
    fn from(payload: ResourceKind) -> Self {
        Self::ResourceUnavailable(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for OwnerIdentity {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::UnixUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for OwnerIdentity {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<UnixUserIdentifier> for ConnectionClass {
    fn from(payload: UnixUserIdentifier) -> Self {
        Self::NonOwnerUser(payload)
    }
}

#[rustfmt::skip]
impl From<SystemPrincipal> for ConnectionClass {
    fn from(payload: SystemPrincipal) -> Self {
        Self::System(payload)
    }
}

#[rustfmt::skip]
impl From<OtherPersonaEngine> for ConnectionClass {
    fn from(payload: OtherPersonaEngine) -> Self {
        Self::OtherPersona(payload)
    }
}

#[rustfmt::skip]
impl From<NetworkPeer> for ConnectionClass {
    fn from(payload: NetworkPeer) -> Self {
        Self::Network(payload)
    }
}

#[rustfmt::skip]
impl From<OwnerIdentity> for MessageOrigin {
    fn from(payload: OwnerIdentity) -> Self {
        Self::LocalOwner(payload)
    }
}

#[rustfmt::skip]
impl From<ConnectionClass> for MessageOrigin {
    fn from(payload: ConnectionClass) -> Self {
        Self::LocalConnection(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentPrincipal> for MessageOrigin {
    fn from(payload: ComponentPrincipal) -> Self {
        Self::Internal(payload)
    }
}

#[rustfmt::skip]
impl From<InternalComponentInstanceOrigin> for MessageOrigin {
    fn from(payload: InternalComponentInstanceOrigin) -> Self {
        Self::InternalComponentInstance(payload)
    }
}

#[rustfmt::skip]
impl From<ChannelIdentifier> for MessageOrigin {
    fn from(payload: ChannelIdentifier) -> Self {
        Self::Channel(payload)
    }
}

#[rustfmt::skip]
impl From<Presence> for Input {
    fn from(payload: Presence) -> Self {
        Self::Announce(payload)
    }
}

#[rustfmt::skip]
impl From<LifecycleQuery> for Input {
    fn from(payload: LifecycleQuery) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentName> for Input {
    fn from(payload: ComponentName) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentIdentity> for Output {
    fn from(payload: ComponentIdentity) -> Self {
        Self::Identified(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentReady> for Output {
    fn from(payload: ComponentReady) -> Self {
        Self::Ready(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentNotReady> for Output {
    fn from(payload: ComponentNotReady) -> Self {
        Self::NotReady(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentHealthReport> for Output {
    fn from(payload: ComponentHealthReport) -> Self {
        Self::HealthReport(payload)
    }
}

#[rustfmt::skip]
impl From<StopAcknowledgement> for Output {
    fn from(payload: StopAcknowledgement) -> Self {
        Self::StopAcknowledged(payload)
    }
}

#[rustfmt::skip]
impl From<RequestUnimplemented> for Output {
    fn from(payload: RequestUnimplemented) -> Self {
        Self::Unimplemented(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Input {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::str::FromStr for Output {
    type Err = DotosDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        DotosSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "dotos-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as DotosEncode>::to_dotos(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_ANNOUNCE: u64 = 0x0000000100000001;
    pub const INPUT_QUERY: u64 = 0x0001000100000001;
    pub const INPUT_STOP: u64 = 0x0002000100000001;
    pub const OUTPUT_IDENTIFIED: u64 = 0x0100000100000001;
    pub const OUTPUT_READY: u64 = 0x0101000100000001;
    pub const OUTPUT_NOT_READY: u64 = 0x0102000100000001;
    pub const OUTPUT_HEALTH_REPORT: u64 = 0x0103000100000001;
    pub const OUTPUT_STOP_ACKNOWLEDGED: u64 = 0x0104000100000001;
    pub const OUTPUT_UNIMPLEMENTED: u64 = 0x0105000100000001;
    pub const HANDSHAKE_REQUEST: u64 = 0xFF00000100000001;
    pub const HANDSHAKE_REPLY: u64 = 0xFF01000100000001;
    pub const ENGINE_REFUSAL: u64 = 0xFF02000100000001;
}

#[rustfmt::skip]
pub enum ContractMarker {}
#[rustfmt::skip]
impl signal_frame::WireContract for ContractMarker {
    const BINDING: signal_frame::ContractBinding = signal_frame::ContractBinding::new(
        match signal_frame::ContractId::try_new(1u32) {
            Ok(contract) => contract,
            Err(_) => panic!("generated contract ID must be nonzero"),
        },
        match signal_frame::WireRevision::try_new(1u16) {
            Ok(revision) => revision,
            Err(_) => panic!("generated wire revision must be nonzero"),
        },
    );
}
#[rustfmt::skip]
/// Why the daemon refused to produce an ordinary reply.
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq
)]
pub enum EngineRefusalReason {
    /// The engine ran and rejected the request with its typed
    /// domain error; the rendered error text is the detail.
    Rejected,
    /// The engine layer could not serve the request at all.
    Unavailable,
}
#[rustfmt::skip]
impl std::fmt::Display for EngineRefusalReason {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Rejected => formatter.write_str("engine rejected the request"),
            Self::Unavailable => formatter.write_str("engine unavailable"),
        }
    }
}
#[rustfmt::skip]
/// The refusal reply a daemon writes when the engine failed, so
/// the caller receives a complete typed frame instead of a closed
/// socket it cannot distinguish from daemon death. The typed
/// engine error stays daemon-side; the wire carries the
/// classification plus the rendered error text.
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineRefusal {
    pub reason: EngineRefusalReason,
    pub detail: String,
}
#[rustfmt::skip]
impl EngineRefusal {
    pub fn rejected(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Rejected,
            detail,
        }
    }
    pub fn unavailable(detail: String) -> Self {
        Self {
            reason: EngineRefusalReason::Unavailable,
            detail,
        }
    }
    pub fn encode_bound_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            signal_frame::SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&short_header::ENGINE_REFUSAL.to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
}
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    FrameEncode,
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    LegacyHeader { contract_id: u32, wire_revision: u16 },
    ContractMismatch { expected: u32, found: u32 },
    UnsupportedWireRevision { contract_id: u32, expected: u16, found: u16 },
    UnknownRoute { root: u8, variant: u8 },
    RouteBodyMismatch { root: u8, variant: u8, body: &'static str },
    UnexpectedFrameBody { found: &'static str },
    OperationCount { found: usize },
    EngineRefused { refusal: EngineRefusal },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::FrameEncode => {
                formatter.write_str("failed to encode bound signal frame")
            }
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::LegacyHeader { contract_id, wire_revision } => {
                write!(
                    formatter,
                    "legacy unbound signal frame ({contract_id}, {wire_revision})"
                )
            }
            Self::ContractMismatch { expected, found } => {
                write!(
                    formatter,
                    "signal contract mismatch: expected {expected}, found {found}"
                )
            }
            Self::UnsupportedWireRevision { contract_id, expected, found } => {
                write!(
                    formatter,
                    "unsupported wire revision for contract {contract_id}: expected {expected}, found {found}"
                )
            }
            Self::UnknownRoute { root, variant } => {
                write!(formatter, "unknown bound signal route ({root}, {variant})")
            }
            Self::RouteBodyMismatch { root, variant, body } => {
                write!(
                    formatter,
                    "bound signal route ({root}, {variant}) does not carry {body}"
                )
            }
            Self::UnexpectedFrameBody { found } => {
                write!(formatter, "expected one request frame, found {found}")
            }
            Self::OperationCount { found } => {
                write!(formatter, "expected one request operation, found {found}")
            }
            Self::EngineRefused { refusal } => {
                write!(formatter, "{}: {}", refusal.reason, refusal.detail)
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}
#[rustfmt::skip]
impl ContractMarker {
    pub fn handshake_request_frame(request: signal_frame::HandshakeRequest) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(0),
            ),
            FrameBody::HandshakeRequest(request),
        )
    }
    pub fn handshake_reply_frame(reply: signal_frame::HandshakeReply) -> Frame {
        Frame::new(
            signal_frame::WireRoute::new(
                signal_frame::RootCode::new(0xff),
                signal_frame::VariantCode::new(1),
            ),
            FrameBody::HandshakeReply(reply),
        )
    }
    pub fn decode_frame(bytes: &[u8]) -> Result<Frame, SignalFrameError> {
        if bytes.len() < signal_frame::SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: bytes.len(),
            });
        }
        let mut header_bytes = [0_u8; signal_frame::SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&bytes[..signal_frame::SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let contract_id = header as u32;
        let wire_revision = (header >> 32) as u16;
        if contract_id == 0 || wire_revision == 0 {
            return Err(SignalFrameError::LegacyHeader {
                contract_id,
                wire_revision,
            });
        }
        if contract_id != 1u32 {
            return Err(SignalFrameError::ContractMismatch {
                expected: 1u32,
                found: contract_id,
            });
        }
        if wire_revision != 1u16 {
            return Err(SignalFrameError::UnsupportedWireRevision {
                contract_id,
                expected: 1u16,
                found: wire_revision,
            });
        }
        let root = (header >> 56) as u8;
        let variant = (header >> 48) as u8;
        match (root, variant) {
            (0, 0)
            | (0, 1)
            | (0, 2)
            | (1, 0)
            | (1, 1)
            | (1, 2)
            | (1, 3)
            | (1, 4)
            | (1, 5)
            | (0xff, 0)
            | (0xff, 1)
            | (0xff, 2) => {}
            _ => {
                return Err(SignalFrameError::UnknownRoute {
                    root,
                    variant,
                });
            }
        }
        if (root, variant) == (0xff, 2) {
            let refusal = rkyv::from_bytes::<
                EngineRefusal,
                rkyv::rancor::Error,
            >(&bytes[signal_frame::SHORT_HEADER_BYTE_COUNT..])
                .map_err(|_| SignalFrameError::ArchiveDecode)?;
            return Err(SignalFrameError::EngineRefused {
                refusal,
            });
        }
        let frame = Frame::decode(bytes).map_err(|_| SignalFrameError::ArchiveDecode)?;
        let header_route = signal_frame::WireRoute::new(
            signal_frame::RootCode::new(root),
            signal_frame::VariantCode::new(variant),
        );
        let body_matches = match frame.body() {
            FrameBody::HandshakeRequest(_) => (root, variant) == (0xff, 0),
            FrameBody::HandshakeReply(_) => (root, variant) == (0xff, 1),
            FrameBody::Request { request, .. } => {
                request.route().is_ok_and(|route| route == header_route)
            }
            FrameBody::Reply { reply, .. } => {
                match reply {
                    signal_frame::Reply::Accepted { per_operation, .. } => {
                        match per_operation.head() {
                            signal_frame::SubReply::Ok(output) => {
                                output.wire_route() == header_route
                            }
                            signal_frame::SubReply::Failed {
                                detail: Some(output),
                                ..
                            } => output.wire_route() == header_route,
                            signal_frame::SubReply::Invalidated
                            | signal_frame::SubReply::Failed { detail: None, .. }
                            | signal_frame::SubReply::Skipped => root == 1,
                        }
                    }
                    signal_frame::Reply::Rejected { .. } => root == 1,
                }
            }
        };
        if !body_matches {
            let body = match frame.body() {
                FrameBody::HandshakeRequest(_) => "handshake request",
                FrameBody::HandshakeReply(_) => "handshake reply",
                FrameBody::Request { .. } => "request",
                FrameBody::Reply { .. } => "reply",
            };
            return Err(SignalFrameError::RouteBodyMismatch {
                root,
                variant,
                body,
            });
        }
        Ok(frame)
    }
    pub fn decode_single_request(
        bytes: &[u8],
    ) -> Result<(signal_frame::ExchangeIdentifier, Input), SignalFrameError> {
        let frame = Self::decode_frame(bytes)?;
        match frame.into_body() {
            FrameBody::Request { exchange, request } => {
                let found = request.payloads().len();
                if found != 1 {
                    return Err(SignalFrameError::OperationCount {
                        found,
                    });
                }
                Ok((exchange, request.payloads.into_head()))
            }
            FrameBody::HandshakeRequest(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake request",
                })
            }
            FrameBody::HandshakeReply(_) => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "handshake reply",
                })
            }
            FrameBody::Reply { .. } => {
                Err(SignalFrameError::UnexpectedFrameBody {
                    found: "reply",
                })
            }
        }
    }
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Announce,
    Query,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(
    feature = "dotos-text",
    derive(dotos::DotosDecode, dotos::DotosDecodeTraced, dotos::DotosEncode)
)]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Identified,
    Ready,
    NotReady,
    HealthReport,
    StopAcknowledged,
    Unimplemented,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Announce(_) => InputRoute::Announce,
            Self::Query(_) => InputRoute::Query,
            Self::Stop(_) => InputRoute::Stop,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Announce(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Query(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::Stop(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(0),
                    signal_frame::VariantCode::new(2),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Announce(_) => short_header::INPUT_ANNOUNCE,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::Stop(_) => short_header::INPUT_STOP,
        }
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Identified(_) => OutputRoute::Identified,
            Self::Ready(_) => OutputRoute::Ready,
            Self::NotReady(_) => OutputRoute::NotReady,
            Self::HealthReport(_) => OutputRoute::HealthReport,
            Self::StopAcknowledged(_) => OutputRoute::StopAcknowledged,
            Self::Unimplemented(_) => OutputRoute::Unimplemented,
        }
    }
    pub fn wire_route(&self) -> signal_frame::WireRoute {
        match self {
            Self::Identified(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(0),
                )
            }
            Self::Ready(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(1),
                )
            }
            Self::NotReady(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(2),
                )
            }
            Self::HealthReport(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(3),
                )
            }
            Self::StopAcknowledged(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(4),
                )
            }
            Self::Unimplemented(_) => {
                signal_frame::WireRoute::new(
                    signal_frame::RootCode::new(1),
                    signal_frame::VariantCode::new(5),
                )
            }
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Identified(_) => short_header::OUTPUT_IDENTIFIED,
            Self::Ready(_) => short_header::OUTPUT_READY,
            Self::NotReady(_) => short_header::OUTPUT_NOT_READY,
            Self::HealthReport(_) => short_header::OUTPUT_HEALTH_REPORT,
            Self::StopAcknowledged(_) => short_header::OUTPUT_STOP_ACKNOWLEDGED,
            Self::Unimplemented(_) => short_header::OUTPUT_UNIMPLEMENTED,
        }
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &["Announce", "Query", "Stop"];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        let route = self.wire_route();
        u64::from(route.root().value()) | (u64::from(route.variant().value()) << 8)
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::BoundExchangeFrame<ContractMarker, Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let request = signal_frame::Request::from_payload(self);
        Frame::new(
            route,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
    pub fn encode_request_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_frame(exchange).encode().map_err(|_| SignalFrameError::FrameEncode)
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let route = self.wire_route();
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::new(
            route,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
    pub fn encode_reply_frame(
        self,
        exchange: signal_frame::ExchangeIdentifier,
    ) -> Result<Vec<u8>, SignalFrameError> {
        self.into_reply_frame(exchange)
            .encode()
            .map_err(|_| SignalFrameError::FrameEncode)
    }
}
